### ISSUE TITLE
Components are causing an invariant error during render

### ISSUE THREAD

**Issue by danschultz** [danschultz/react.dart#1]
When rendering a component through dart2js, React is reporting an invariant error and the component isn't being rendered.

The code in React that's reporting the error is here: https://github.com/danschultz/react.dart/blob/master/lib/react.js#L6089. And this is where React is calling `render()`: https://github.com/danschultz/react.dart/blob/master/lib/react.js#L6063

```
Uncaught Error: Invariant Violation: ReactCompositeComponent.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

It appears that the `ReactElement` that is being returned by the Dart component's `render()` method is being translated into a `DartObject`. React doesn't know how to handle this and reports an invariant error.

Repro steps:
1. Run `pub serve example/`
2. Open `http://localhost:8080` in Chrome.

**Comment by jacob314** [comment]
To use the new JS interop you will need to make sure you do not use the old dart:js interop at all in your code. Eliminate all uses of dart:js and let me know whether you still encounter the issue.
JsObject uses wrapping so supporting it would cripple the performance of JS interop performance and mean we couldn't pass Arrays/Lists back and forth without wrapping.

**Comment by danschultz** [comment]
@jacob314 thanks for responding. I've removed `dart:js`, but I'm seeing the same issue.

I think I've narrowed the problem to returning a value inside `allowInteropCaptureThis`.

**Comment by jacob314** [comment]
Thanks. There is a one line fix for dart:js. Testing it locally now.

**Comment by danschultz** [comment]
Great, good to hear!

**Comment by jacob314** [comment]
Out for review: 
https://codereview.chromium.org/1412193009/

**Comment by jacob314** [comment]
FYI there are still a couple uses of dart:js in react.dart 
and one case where I'm not sure allowInterop is called where it should be.
here's a CL on react.dart with some tweaks I made locally when looking at what the issue was.
https://codereview.appspot.com/274830043

**Comment by danschultz** [comment]
@jacob314 thanks! When do you expect this to be on the development channel?

Also, is there an easier way to pass a Map to JS without having to create a wrapper class in Dart? I can see use cases where you'd need to pass a Map to JS that has arbitrary key/values.

> FYI there are still a couple uses of dart:js in react.dart 

Sorry, I had removed them locally without pushing the changes.

**Comment by jacob314** [comment]
Depends what you mean by arbitrary. All cases where the set of property names is known at compile time should be handled by the extremely efficient pattern:

@Js
class ExamplePropertiesToPassToDart {
  external factory ExamplePropertiesToPassToDart({foo, bar, baz});
  external get foo;
  external get bar;
  external get baz;
}

If the property names aren't known at compile time, currently you'll have to write something like the following.
I plan to soon provide a standardized util of helper methods in package:js that support manipulating JS objects from dart. 

// From js:
JsUtil = { setProperty: function(obj, propertyName, value) { obj[propertyName] = value; } };

// From dart:
@Js("JsUtil.setProperty")
external setProperty(obj, String propertyName, value);

**Comment by danschultz** [comment]
Cool, the later is what I'm looking for.

**Comment by jacob314** [comment]
Stay tuned for a JSNative utility library of static methods that provides bare metal support for setProperty, getProperty, hasProperty, etc. Looks like it is something I need to add sooner rather than later.

**Comment by danschultz** [comment]
@jacob314 building on that, having an interop object that mimics the full API of JS's `Object` would be useful. Also, it'd be convenient to be able to pass Dart's futures and JS's promises back and forth.

**Comment by jacob314** [comment]
Please star this bug if you care about passing Dart futures and JS promises back and forth.
https://github.com/dart-lang/sdk/issues/24679

Nothing is stopping you from writing
@JS  <-- heads up @Js changed to @JS in the latest release of 1.13 to match the style guide.
class JavaScriptObject {
 // All methods on JavaScript object
}

The thing that will be missing is you currently aren't allowed to add 
operator [] on this class as that would hurt general dart2js performance too much
and you won't be able to express

'foo' in someJavaScriptObject

which is why those JS concepts need to go in static methods.

**Comment by danschultz** [comment]
> Nothing is stopping you from writing
> @JS <-- heads up @Js changed to @JS in the latest release of 1.13 to match the style guide.
> class JavaScriptObject {
>     // All methods on JavaScript object
> }

Sure. I guess my thinking is that the new interop has good mappings between JS's built in types (i.e. arrays, numbers, strings, DOM elements, and typed data), but is missing support for `Map`s and being able to interact with them using instance level methods.

**Comment by jacob314** [comment]
Yes.
I would like to be able to support
anyJSObject[propertyName]
Maybe we'll figure out how to without negatively impacting general dart2js performance. If not, static methods will need to suffice.

**Comment by danschultz** [comment]
This fixed the issue, closing.
